### ISSUE TITLE
Open Source IT ?

### ISSUE THREAD

**Issue by ABalanuta** [BennSaturn/AISS_Project#1]
Como é que o que que fazemos com isto ?
Ja falaste com o prof. R.Chavez :interrobang:

**Comment by BennSaturn** [comment]
Não faço a mais pequena ideia. Depois de entregarmos a tese pergunta-se ok?

**Comment by ABalanuta** [comment]
ok

**Comment by ABalanuta** [comment]
Vamos fazer release a isto, sem dar indicaçoes. Já lá vão uns anos. Era bom tambem descrever o projecto. O que achas ?

**Comment by BennSaturn** [comment]
Vou meter isto público então, ok? e transferi o ownership para o teu git porque assim tomas melhor conta disso.

**Comment by ABalanuta** [comment]
ok, no prob
